# Flash programmer parameters file
# Automatically generated by SDK (30/09/2011 17:02:28).

set FLASH_FILE                    "C:/sp605_bist/SDK/SDK_Workspace_35/hw_platform_0/cache/hello_sysace.elf.srec"
set FLASH_BASEADDR                0x7C000000
set FLASH_PROG_OFFSET             0x00500000
set FLASH_BUSWIDTH                16
set SCRATCH_BASEADDR              0x50000000
set SCRATCH_LEN                   0x08000000
set TARGET_TYPE                   "MICROBLAZE"
set PROC_INSTANCE                 "microblaze_0"
set EXTRA_COMPILER_FLAGS          "-mno-xl-soft-mul "
set XMD_CONNECT                   "connect mb mdm  -debugdevice cpunr 1"
set ENDIANNESS                    "BE"
